INSERT INTO `location_biome_table` (`name`, `identifier`)
VALUES
    ("The Void", "the_void"),
    ("Plains", "plains"),
    ("Sunflower Plains", "sunflower_plains"),
    ("Snowy Plains", "snowy_plains"),
    ("Ice Spikes", "ice_spikes"),
    ("Desert", "desert"),
    ("Swamp", "swamp"),
    ("Mangrove Swamp", "mangrove_swamp"),
    ("Forest", "forest"),
    ("Flower Forest", "flower_forest"),
    ("Birch Forest", "birch_forest"),
    ("Dark Forest", "dark_forest"),
    ("Old Growth Birch Forest", "old_growth_birch_forest"),
    ("Old Growth Pine Taiga", "old_growth_pine_taiga"),
    ("Old Growth Spruce Taiga", "old_growth_spruce_taiga"),
    ("Taiga", "taiga"),
    ("Snowy Taiga", "snowy_taiga"),
    ("Savanna", "savanna"),
    ("Savanna Plateau", "savanna_plateau"),
    ("Windswept Hills", "windswept_hills"),
    ("Windswept Gravelly Hills", "windswept_gravelly_hills"),
    ("Windswept Forest", "windswept_forest"),
    ("Windswept Savanna", "windswept_savanna"),
    ("Jungle", "jungle"),
    ("Sparse Jungle", "sparse_jungle"),
    ("Bamboo Jungle", "bamboo_jungle"),
    ("Badlands", "badlands"),
    ("Eroded Badlands", "eroded_badlands"),
    ("Wooded Badlands", "wooded_badlands"),
    ("Meadow", "meadow"),
    ("Grove", "grove"),
    ("Snowy Slopes", "snowy_slopes"),
    ("Frozen Peaks", "frozen_peaks"),
    ("Jagged Peaks", "jagged_peaks"),
    ("Stony Peaks", "stony_peaks"),
    ("River", "river"),
    ("Frozen River", "frozen_river"),
    ("Beach", "beach"),
    ("Snowy Beach", "snowy_beach"),
    ("Stony Shore", "stony_shore"),
    ("Warm Ocean", "warm_ocean"),
    ("Lukewarm Ocean", "lukewarm_ocean"),
    ("Deep Lukewarm Ocean", "deep_lukewarm_ocean"),
    ("Ocean", "ocean"),
    ("Deep Ocean", "deep_ocean"),
    ("Cold Ocean", "cold_ocean"),
    ("Deep Cold Ocean", "deep_cold_ocean"),
    ("Frozen Ocean", "frozen_ocean"),
    ("Deep Frozen Ocean", "deep_frozen_ocean"),
    ("Mushroom Fields", "mushroom_fields"),
    ("Dripstone Caves", "dripstone_caves"),
    ("Lush Caves", "lush_caves"),
    ("Deep Dark", "deep_dark"),
    ("Nether Wastes", "nether_wastes"),
    ("Warped Forest", "warped_forest"),
    ("Crimson Forest", "crimson_forest"),
    ("Soul Sand Valley", "soul_sand_valley"),
    ("Basalt Deltas", "basalt_deltas"),
    ("The End", "the_end"),
    ("End Highlands", "end_highlands"),
    ("End Midlands", "end_midlands"),
    ("Small End Islands", "small_end_islands"),
    ("End Barrens", "end_barrens");
